### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by djmoch** [vi/imlib2-heic#1]
I'd like to package this for another distro, but need to know what the license terms are before I can do that

**Comment by vi** [comment]
I'm not adding any additional restrictions, the license is intersection of libheif's and imlib2's licences, so it's probably effectively LGPL.

Without linking to libheif it looks like 3-clause BSD.

**Comment by djmoch** [comment]
> so it's probably effectively LGPL.

I can run with that. You might want to add a license file to avoid having to repeat this conversation with other packagers.

**Comment by astralchan** [comment]
Can we re-open this? I'm trying to package this [here](https://github.com/void-linux/void-packages/pull/27814), at the very least having a dedicated LICENSE file would make packaging so much easier.

**Comment by vi** [comment]
Which licence file should it contain? A copy of libheic's or BSD's?

**Comment by astralchan** [comment]
A copy of the BSD 3 Clause license

**Comment by vi** [comment]
Done. Shall I create a tag?

**Comment by astralchan** [comment]
Yes, as it must have a release to be packaged.

**Comment by vi** [comment]
Done: https://github.com/vi/imlib2-heic/releases/tag/v0.1.1
