### ISSUE TITLE
[SOLVED] imlib2-heic crashes with segmentation fault for iPhone HEIF/HEIC files or shows broken images

### ISSUE THREAD

**Issue by Mexx77** [vi/imlib2-heic#2]
Hey,

I would love to contribute to this project. I don't really know where to start looking though. Here is my problem.
Im using feh which uses imlib2 and I would like to see my iPhone HEIF/HEIC files so I installed imlib2-heic also.
It either crashes with such a segmentation fault:

```
Stack trace of thread 20303:
                #0  0x00007fb99b303497 load (heic.so + 0x1497)
                #1  0x00007fb99c31687c n/a (libImlib2.so.1 + 0x2287c)
                #2  0x00007fb99c317381 n/a (libImlib2.so.1 + 0x23381)
                #3  0x00007fb99c2fcd2f imlib_load_image_with_error_return (libImlib2.so.1 + 0x8d2f)
                #4  0x0000560177fa5de9 n/a (feh + 0xcde9)
                #5  0x0000560177fbbb24 n/a (feh + 0x22b24)
                #6  0x0000560177fb4e8c n/a (feh + 0x1be8c)
                #7  0x0000560177fad6d6 n/a (feh + 0x146d6)
                #8  0x0000560177fadcbf n/a (feh + 0x14cbf)
                #9  0x0000560177fa013e n/a (feh + 0x713e)
                #10 0x00007fb99c154002 __libc_start_main (libc.so.6 + 0x27002)
                #11 0x0000560177fa026e n/a (feh + 0x726e)
```

Or shows images pixelated in black/white with artifacts like so:

![Screenshot from 2020-08-16 16-15-48](https://user-images.githubusercontent.com/173655/90336407-08b37800-dfdc-11ea-85c0-4dae77a51085.png)
 
Can you help me?

**Comment by vi** [comment]
Does it also work correctly for some of the files?
If so, can you attach a sample file which shows the malfunction?

**Comment by Mexx77** [comment]
Does not work for any of them. They were taken with an iPhone X. Here is an example. Thanks for the quick response :100: :smile:
[IMG_3010.HEIC.zip](https://github.com/vi/imlib2-heic/files/5080955/IMG_3010.HEIC.zip)

**Comment by Mexx77** [comment]
![Screenshot from 2020-08-16 18-10-35](https://user-images.githubusercontent.com/173655/90338774-5c2dc200-dfec-11ea-9abe-de5f427bf1b2.png)
Left: original HEIC opened with feh + imlib2-heic
Right: converted JPEG. Thats how it should look like

**Comment by vi** [comment]
On my system it looks OK, like the one on the right.

Are you building the library from source or using a pre-built package?

What version of imlib2 have you got? I am currently using `1.5.1-1` from Debian.

**Comment by vi** [comment]
After updating it to `1.6.1-2~bpo10+1` it still works allright.

**Comment by Mexx77** [comment]
os: arch linux
imlib2: 1.7.0-1
imlib2-heic: tried package https://aur.archlinux.org/packages/imlib2-heic/ but also cloned this github repo and built it myself

maybe imlib2 1.7 is incompatible. Could you try that?

Edit:
downgraded imlib2 to both 1.6.1-1 and 1.6.1-2 and its broken with these versions as well :confused:

**Comment by Mexx77** [comment]
any idea what else could cause the issue?

**Comment by vi** [comment]
Are you open for trying various special versions and reporting various debugging info (i.e. debugging together)?

**Comment by Mexx77** [comment]
yes of course! I am also open for a remote debugging session via zoom or teams etc.

**Comment by vi** [comment]
May be caused by different version of libheif: I have `1.3.2-2~deb10u1`, Arch seems to have `libheif 1.7.0-2`.

**Comment by vi** [comment]
Reproduced the issue by building and running imlib2-heic in Docker with Arch. It shows the picture like on the left.

**Comment by vi** [comment]
Updated libheif to `1.6.1-1~bpo10+1` on my Debian - feh still shows the correct picture.

**Comment by vi** [comment]
May be a bug in libheif v1.7.

Built from source `v1.6.2` - normal picture
Built from source `v1.7.0` - distorted picture
Built from source `master` (b6311f71ad90085ef7efd10e15c717900c97cc93) - normal picture.

**Comment by vi** [comment]
Done `git bisect`. It pointed to commits:

* Causes issue: https://github.com/strukturag/libheif/commit/bca0162018df9a32d21c05aad1fa203881fa7813
* Fixes issue: https://github.com/strukturag/libheif/commit/a070738a81a253ad13bc63fe4cee805c8833da7b

So I belive it's not `imlib2-heic`'s issue.
Use `libheif` that is not version 1.7.0 (but either older or newer).

**Comment by Mexx77** [comment]
good catch! downgraded to libheif 1.6.2 and it works :)
since it worked for you with the master, we can assume, its gonna be fixed in the next release of libheif, right?

**Comment by vi** [comment]
Yes.
